### PR TITLE
Add machine data source

### LINKED ISSUE #169: feature request: datasource machine
### Use case

I want to be able to reference already existing Juju machines in my plan, without having to import them.

### Feature

```tf
data "juju_machine" "machine" {
  model      = "my-model"
  machine_id = "2"
}

###

resource "juju_application" "my-app" {
  model     = "my-model"
  placement = data.juju_machine.machine.machine_id
  ...
}

```

### PR DESCRIPTION
**Pull request by gboutry**
## Description

This PR add a Machine data source to be able to reference already provisioned machine inside a terraform plan.

fix #169

## Type of change

Please mark if proceeds.

- [ ] New resource (a new resource in the schema) ? This is a data source and not a resource, new field ?
- [ ] Changed resource (changes in an existing resource)
- [ ] Logic changes in resources (the API interaction with Juju has been changed)
- [ ] Test changes (one or several tests have been changed)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Other: Add a data source

## Environment

- Juju controller version: 3.1.0
- Terraform version: 1.4.0

## QA steps

Manual QA steps should be done to test this PR.

```tf
provider juju {}

resource "juju_model" "dev" {
  name = "dev"
}

resource "juju_machine" "dev" {
  name   = "dev-machine"
  model  = juju_model.dev.name
  series = "jammy"
}

data "juju_machine" "dev" {
  model      = juju_model.dev.name 
  machine_id = juju_machine.dev.machine_id
}
```

# Additional notes

### CODE REVIEW

**Comment by gboutry** [comment]
Force push is fixing formatting issue.

**Comment by gboutry** [comment]
I can't get `go generate` to work to day, I keep getting timed out, it worked yesterday... I will try later in the day.

**Comment by gboutry** [comment]
Force push is applying changes from `go generate`

**Comment by gboutry** [comment]
Failure seems related to #168

**Review by juanmanuel-tirado — APPROVED** [review]
I think this is ready for landing. We can ignore the failing tests. This has to be addressed in #175
Thanks

PS: Please submit a feature request before submitting code. I will be more explicit on the how-to-contribute guidelines.

**Comment by gboutry** [comment]
Is there something wrong with #169 ? is that not the right place or template ?

**Comment by juanmanuel-tirado** [comment]
It's perfectly OK. But imagine we do not want to proceed with that feature or we want to proceed in another way. In that case, we could have say no to this because importing fixes the problem and you would have wasted your time. Anyway, thanks for the PR :)

**Comment by gboutry** [comment]
Okay I understand, thank you

**Pull request merged**
