### PR TITLE
Remove integration from state if it was removed manually (#186)

### PR DESCRIPTION
**Pull request by amandahla**
## Description

Currently, if integration is removed manually, terraform plan fails with "no integrations exist in specified model". This PR  changes the behavior to remove it from the state instead.

## Type of change

Please mark if proceeds.

- [ ] New resource (a new resource in the schema)
- [ ] Changed resource (changes in an existing resource)
- [ ] Logic changes in resources (the API interaction with Juju has been changed)
- [ ] Test changes (one or several tests have been changed)
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other (describe)

## Environment

- Juju controller version: 2.9.42
- Terraform version: 1.4.4

## QA steps

Manual QA steps should be done to test this PR.

The same that was reported in issue https://github.com/juju/terraform-provider-juju/issues/186

# Additional notes

It might be worth doing this for all the resources and also creating a specific error for that instead of checking the error message.

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
The situation reported in #186 cannot be reproduced after #189 was landed. This is a good check.

Thanks for the PR!!

**Review by juanmanuel-tirado — APPROVED** [review]

**Comment by juanmanuel-tirado** [comment]
@amandahla I'm OK with the changes. Failing tests are not due to these changes. Ready to merge if you're OK with the PR.

**Comment by juanmanuel-tirado** [comment]
Fix #186 
Fix #187

**Comment by amandahla** [comment]
> @amandahla I'm OK with the changes. Failing tests are not due to these changes. Ready to merge if you're OK with the PR.

Awesome! Thanks.

**Pull request merged**
